/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBitacoraRouteImport } from './routes/_authenticated/bitacora'
import { Route as AuthenticatedColoresMapaRouteImport } from './routes/_authenticated/colores-mapa'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedEstructuraRouteImport } from './routes/_authenticated/estructura'
import { Route as AuthenticatedLotesRouteImport } from './routes/_authenticated/lotes'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBitacoraRoute = AuthenticatedBitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColoresMapaRoute =
  AuthenticatedColoresMapaRouteImport.update({
    id: '/colores-mapa',
    path: '/colores-mapa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstructuraRoute = AuthenticatedEstructuraRouteImport.update({
  id: '/estructura',
  path: '/estructura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLotesRoute = AuthenticatedLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bitacora': typeof AuthenticatedBitacoraRoute
  '/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/estructura': typeof AuthenticatedEstructuraRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bitacora': typeof AuthenticatedBitacoraRoute
  '/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/estructura': typeof AuthenticatedEstructuraRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bitacora': typeof AuthenticatedBitacoraRoute
  '/_authenticated/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/estructura': typeof AuthenticatedEstructuraRoute
  '/_authenticated/lotes': typeof AuthenticatedLotesRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bitacora'
    | '/colores-mapa'
    | '/configuracion'
    | '/estructura'
    | '/lotes'
    | '/plano'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bitacora'
    | '/colores-mapa'
    | '/configuracion'
    | '/estructura'
    | '/lotes'
    | '/plano'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bitacora'
    | '/_authenticated/colores-mapa'
    | '/_authenticated/configuracion'
    | '/_authenticated/estructura'
    | '/_authenticated/lotes'
    | '/_authenticated/plano'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bitacora': {
      id: '/_authenticated/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof AuthenticatedBitacoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colores-mapa': {
      id: '/_authenticated/colores-mapa'
      path: '/colores-mapa'
      fullPath: '/colores-mapa'
      preLoaderRoute: typeof AuthenticatedColoresMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estructura': {
      id: '/_authenticated/estructura'
      path: '/estructura'
      fullPath: '/estructura'
      preLoaderRoute: typeof AuthenticatedEstructuraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lotes': {
      id: '/_authenticated/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AuthenticatedLotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBitacoraRoute: typeof AuthenticatedBitacoraRoute
  AuthenticatedColoresMapaRoute: typeof AuthenticatedColoresMapaRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedEstructuraRoute: typeof AuthenticatedEstructuraRoute
  AuthenticatedLotesRoute: typeof AuthenticatedLotesRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBitacoraRoute: AuthenticatedBitacoraRoute,
  AuthenticatedColoresMapaRoute: AuthenticatedColoresMapaRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedEstructuraRoute: AuthenticatedEstructuraRoute,
  AuthenticatedLotesRoute: AuthenticatedLotesRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
