/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApartadosRouteImport } from './routes/_authenticated/apartados'
import { Route as AuthenticatedBitacoraRouteImport } from './routes/_authenticated/bitacora'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCobranzaRouteImport } from './routes/_authenticated/cobranza'
import { Route as AuthenticatedColoresMapaRouteImport } from './routes/_authenticated/colores-mapa'
import { Route as AuthenticatedComisionesRouteImport } from './routes/_authenticated/comisiones'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedDesistimientosRouteImport } from './routes/_authenticated/desistimientos'
import { Route as AuthenticatedEstructuraRouteImport } from './routes/_authenticated/estructura'
import { Route as AuthenticatedLotesRouteImport } from './routes/_authenticated/lotes'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApartadosRoute = AuthenticatedApartadosRouteImport.update({
  id: '/apartados',
  path: '/apartados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBitacoraRoute = AuthenticatedBitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCobranzaRoute = AuthenticatedCobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColoresMapaRoute =
  AuthenticatedColoresMapaRouteImport.update({
    id: '/colores-mapa',
    path: '/colores-mapa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComisionesRoute = AuthenticatedComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesistimientosRoute =
  AuthenticatedDesistimientosRouteImport.update({
    id: '/desistimientos',
    path: '/desistimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstructuraRoute = AuthenticatedEstructuraRouteImport.update({
  id: '/estructura',
  path: '/estructura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLotesRoute = AuthenticatedLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apartados': typeof AuthenticatedApartadosRoute
  '/bitacora': typeof AuthenticatedBitacoraRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobranza': typeof AuthenticatedCobranzaRoute
  '/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/comisiones': typeof AuthenticatedComisionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/desistimientos': typeof AuthenticatedDesistimientosRoute
  '/estructura': typeof AuthenticatedEstructuraRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apartados': typeof AuthenticatedApartadosRoute
  '/bitacora': typeof AuthenticatedBitacoraRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobranza': typeof AuthenticatedCobranzaRoute
  '/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/comisiones': typeof AuthenticatedComisionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/desistimientos': typeof AuthenticatedDesistimientosRoute
  '/estructura': typeof AuthenticatedEstructuraRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apartados': typeof AuthenticatedApartadosRoute
  '/_authenticated/bitacora': typeof AuthenticatedBitacoraRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cobranza': typeof AuthenticatedCobranzaRoute
  '/_authenticated/colores-mapa': typeof AuthenticatedColoresMapaRoute
  '/_authenticated/comisiones': typeof AuthenticatedComisionesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/desistimientos': typeof AuthenticatedDesistimientosRoute
  '/_authenticated/estructura': typeof AuthenticatedEstructuraRoute
  '/_authenticated/lotes': typeof AuthenticatedLotesRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apartados'
    | '/bitacora'
    | '/clientes'
    | '/cobranza'
    | '/colores-mapa'
    | '/comisiones'
    | '/configuracion'
    | '/desistimientos'
    | '/estructura'
    | '/lotes'
    | '/plano'
    | '/usuarios'
    | '/vendedores'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apartados'
    | '/bitacora'
    | '/clientes'
    | '/cobranza'
    | '/colores-mapa'
    | '/comisiones'
    | '/configuracion'
    | '/desistimientos'
    | '/estructura'
    | '/lotes'
    | '/plano'
    | '/usuarios'
    | '/vendedores'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apartados'
    | '/_authenticated/bitacora'
    | '/_authenticated/clientes'
    | '/_authenticated/cobranza'
    | '/_authenticated/colores-mapa'
    | '/_authenticated/comisiones'
    | '/_authenticated/configuracion'
    | '/_authenticated/desistimientos'
    | '/_authenticated/estructura'
    | '/_authenticated/lotes'
    | '/_authenticated/plano'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendedores'
    | '/_authenticated/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apartados': {
      id: '/_authenticated/apartados'
      path: '/apartados'
      fullPath: '/apartados'
      preLoaderRoute: typeof AuthenticatedApartadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bitacora': {
      id: '/_authenticated/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof AuthenticatedBitacoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobranza': {
      id: '/_authenticated/cobranza'
      path: '/cobranza'
      fullPath: '/cobranza'
      preLoaderRoute: typeof AuthenticatedCobranzaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colores-mapa': {
      id: '/_authenticated/colores-mapa'
      path: '/colores-mapa'
      fullPath: '/colores-mapa'
      preLoaderRoute: typeof AuthenticatedColoresMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comisiones': {
      id: '/_authenticated/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof AuthenticatedComisionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desistimientos': {
      id: '/_authenticated/desistimientos'
      path: '/desistimientos'
      fullPath: '/desistimientos'
      preLoaderRoute: typeof AuthenticatedDesistimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estructura': {
      id: '/_authenticated/estructura'
      path: '/estructura'
      fullPath: '/estructura'
      preLoaderRoute: typeof AuthenticatedEstructuraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lotes': {
      id: '/_authenticated/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AuthenticatedLotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApartadosRoute: typeof AuthenticatedApartadosRoute
  AuthenticatedBitacoraRoute: typeof AuthenticatedBitacoraRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCobranzaRoute: typeof AuthenticatedCobranzaRoute
  AuthenticatedColoresMapaRoute: typeof AuthenticatedColoresMapaRoute
  AuthenticatedComisionesRoute: typeof AuthenticatedComisionesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDesistimientosRoute: typeof AuthenticatedDesistimientosRoute
  AuthenticatedEstructuraRoute: typeof AuthenticatedEstructuraRoute
  AuthenticatedLotesRoute: typeof AuthenticatedLotesRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApartadosRoute: AuthenticatedApartadosRoute,
  AuthenticatedBitacoraRoute: AuthenticatedBitacoraRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCobranzaRoute: AuthenticatedCobranzaRoute,
  AuthenticatedColoresMapaRoute: AuthenticatedColoresMapaRoute,
  AuthenticatedComisionesRoute: AuthenticatedComisionesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDesistimientosRoute: AuthenticatedDesistimientosRoute,
  AuthenticatedEstructuraRoute: AuthenticatedEstructuraRoute,
  AuthenticatedLotesRoute: AuthenticatedLotesRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
